//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GununNasıldı.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisiler
    {
        public int kisiId { get; set; }
        public string kisiIsim { get; set; }
        public string kisiSoyisim { get; set; }
        public string kisiEposta { get; set; }
        public Nullable<int> YaziId { get; set; }
        public string kisiResimAdres { get; set; }
        public string sifre { get; set; }
    }
}
