//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GununNasıldı.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yazilar
    {
        public string yaziId { get; set; }
        public string yaziIcerikAdres { get; set; }
        public Nullable<int> kisiId { get; set; }
    }
}
